name: Builder

on:
  push:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 7 * * 1'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: 'Determine current Caddy version'
        id: current-caddy
        uses: flownative/action-docker-get-label@v1.0.1
        with:
          image: ghcr.io/iksaku/caddy-docker
          label: version.caddy
      - name: 'Determine current Caddy-Docker Proxy version'
        id: current-proxy
        uses: flownative/action-docker-get-label@v1.0.1
        with:
          image: ghcr.io/iksaku/caddy-docker
          label: version.caddy-docker-proxy

      - name: 'Fetch latest Caddy release'
        id: caddy
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: caddyserver/caddy
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Fetch latest Caddy-Docker Proxy release'
        id: proxy
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: lucaslorentz/caddy-docker-proxy
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 'Compare versions'
        id: version
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "CADDY_VERSION=${{ steps.caddy.outputs.release }}" | sed -r 's/=v/=/' >> $GITHUB_ENV
          echo "CADDY_DOCKER_PROXY_VERSION=${{ steps.proxy.outputs.release }}" | sed -r 's/=v/=/' >> $GITHUB_ENV

          if [ "${{ steps.current-caddy.outputs.value }}" == "${{ steps.caddy.outputs.release }}" ]; then
            echo "Caddy is up to date: ${{ steps.caddy.outputs.release }}"
          else
            echo "A new Caddy version is available: ${{ steps.caddy.outputs.release }}"
            echo "Currently using: ${{ steps.current-caddy.outputs.value }}"
            echo "UP_TO_DATE=false" >> $GITHUB_ENV
          fi

          if [ "${{ steps.current-proxy.outputs.value }}" == "${{ steps.proxy.outputs.release }}" ]; then
            echo "Caddy-Docker Proxy is up to date: ${{ steps.proxy.outputs.release }}"
          else
            echo "A new Caddy-Docker Proxy version is available: ${{ steps.proxy.outputs.release }}"
            echo "Currently using: ${{ steps.current-proxy.outputs.value }}"
            echo "UP_TO_DATE=false" >> $GITHUB_ENV
          fi
      
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'schedule' || env.UP_TO_DATE == 'false' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        if: ${{ github.event_name != 'schedule' || env.UP_TO_DATE == 'false' }}
        uses: docker/build-push-action@v5
        with:
          build-args: |
            CADDY_VERSION=${{ env.CADDY_VERSION }}
            CADDY_DOCKER_PROXY_VERSION=${{ env.CADDY_DOCKER_PROXY_VERSION }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/iksaku/caddy-docker:latest,ghcr.io/iksaku/caddy-docker:${{ env.DATE }}